In [1]:
import sys
import os
import math
import re
from collections import defaultdict
import numpy as np

In [2]:
input_file = sys.argv[1]

print('PLANET DISTANCE')

with open('A-small-practice.in') as f:
    file_lines = f.readlines()
f.close()

PLANET DISTANCE


In [3]:
def cmpt(string):
    e1 = ''
    e2 = ''
    i=0
    while string[i]!=' ':
        if string[i] == '\n':
            return e1,e2
            break
        e1=e1+string[i]
        i+=1
    j=i+1
    while string[j]!='\n':
        e2=e2+string[j]
        j+=1
    return e1,e2
    
    

In [4]:
def findcircle_dfs(graph,n,init):
    path = []
    edge = []
    circle = []
    color = np.zeros(n+1)
    planet = init
    path0,circle0 = dfs(graph,planet,n,color,path,edge,circle)
    return path0,circle0

def dfs(graph,planet,n,color,path,edge,circle):
    color[int(planet)] = 1
    path.append(planet)
    for i in range(n):
        if cmpt(graph[i])[0]==planet and color[int(cmpt(graph[i])[1])]==0:
            edge.append(i)
            dfs(graph,cmpt(graph[i])[1],n,color,path,edge,circle)
              
        elif cmpt(graph[i])[0]==planet and color[int(cmpt(graph[i])[1])]==1 and edge.count(i)<1:
            if cmpt(graph[i])[1] not in circle:
                circle.append(cmpt(graph[i])[1])
            if cmpt(graph[i])[0] not in circle:
                circle.append(cmpt(graph[i])[0])
            

        elif cmpt(graph[i])[1]==planet and color[int(cmpt(graph[i])[0])] == 0:
            edge.append(i)
            dfs(graph,cmpt(graph[i])[0],n,color,path,edge,circle)

        elif cmpt(graph[i])[1]==planet and color[int(cmpt(graph[i])[0])] == 1 and edge.count(i)<1:
            if cmpt(graph[i])[0] not in circle:
                circle.append(cmpt(graph[i])[0])
            if cmpt(graph[i])[1] not in circle:
                circle.append(cmpt(graph[i])[1])
                
    color[int(planet)] = 2
    return path,circle

In [5]:
def distance_bfs(graph,circle,n):
    color = np.zeros(n+1)
    distance = np.zeros(n+1)
    queue = []
    for planet in circle:
        color[int(planet)] = 2
    for planet in circle:
        queue.append(planet)
        while len(queue)>0:
            u = queue.pop(0)
            for i in range(n):
                if cmpt(graph[i])[0] == u and color[int(cmpt(graph[i])[1])] == 0:
                    color[int(cmpt(graph[i])[1])] = 1
                    distance[int(cmpt(graph[i])[1])] = distance[int(u)] + 1
                    queue.append(cmpt(graph[i])[1])
            
                elif cmpt(graph[i])[1] == u and color[int(cmpt(graph[i])[0])] == 0:
                    color[int(cmpt(graph[i])[0])] = 1
                    distance[int(cmpt(graph[i])[0])] = distance[int(u)] + 1
                    queue.append(cmpt(graph[i])[0])
            color[int(u)] = 2
    return distance

In [6]:
def output(space,case,n):
    pln = np.zeros(n)
    for i in range(n): 
        p1 = cmpt(space[i])[0]
        p2 = cmpt(space[i])[1]
        pln[int(p1)-1]+=1
        pln[int(p2)-1]+=1
    inits = np.where(pln>1)[0]
    treasure_circle = []
    for init in inits:
        path0,circle= findcircle_dfs(space,n,str(init+1))
        for item in circle:
            if item not in treasure_circle:
                treasure_circle.append(item)
    distance = distance_bfs(space,treasure_circle,n)
    print('Case #%d:' %case)
    print(distance[1:])

In [7]:
case = 1
N = int(cmpt(file_lines[0])[0])
L = len(file_lines)
i = 1
space = []
n = int(cmpt(file_lines[1])[0])
while i < L:
    e1, e2 = cmpt(file_lines[i])
    if e2 == '' and len(space) > 0:
        output(space,case,n)
        space = []
        n = int(e1)
        case += 1
    elif e2!='':
        space.append(file_lines[i])
    if i == L-1:
        output(space,case,n)
    i+=1
        

Case #1:
[1. 0. 0. 0. 1.]
Case #2:
[0. 0. 0.]
Case #3:
[0. 0. 1. 2. 0. 1.]
Case #4:
[0. 1. 0. 1. 1. 2. 1. 1. 0. 0. 1. 1. 1. 2. 2. 0. 2. 3. 2. 2. 3. 1.]
Case #5:
[1. 2. 2. 2. 3. 0. 3. 0. 0.]
Case #6:
[0. 0. 0. 0.]
Case #7:
[0. 0. 0. 0. 1. 1. 1. 1. 2. 0. 2. 3. 1. 1. 2. 2. 2. 3. 0. 4. 4. 1. 2.]
Case #8:
[1. 2. 2. 0. 0. 3. 0.]
Case #9:
[0. 0. 1. 0. 1. 2. 0. 1. 1. 2. 0. 1. 2. 1. 2. 2. 2.]
Case #10:
[0. 0. 0. 1.]
Case #11:
[1. 0. 0. 1. 1. 0.]
Case #12:
[0. 0. 1. 2. 1. 0. 1. 2. 1. 2. 2.]
Case #13:
[0. 1. 1. 0. 2. 2. 1. 3. 1. 4. 4. 0. 1. 2. 5. 2. 3. 4. 5. 5. 5. 0.]
Case #14:
[0. 1. 0. 1. 0. 0.]
Case #15:
[1. 2. 0. 3. 0. 3. 0. 1. 2. 1. 3. 0. 4. 3.]
Case #16:
[1. 2. 0. 0. 0. 0. 1. 0. 3. 2. 1. 2. 3. 3. 0.]
Case #17:
[4. 5. 3. 2. 1. 0. 0. 1. 2. 4. 3. 4. 2. 1. 5. 0. 1. 2. 2.]
Case #18:
[0. 0. 0. 1. 1.]
Case #19:
[2. 1. 2. 0. 0. 3. 3. 1. 2. 4. 4. 3. 5. 0. 4. 3. 5. 3. 5. 1. 6. 2. 4. 5.]
Case #20:
[0. 0. 1. 1. 2. 2. 3. 3. 3. 4. 4. 5. 0. 2. 0. 5. 4. 0. 1. 0. 2. 3. 5. 0.
 4. 4. 1. 1. 3. 4.]
Case #21:
[0